apiVersion: v1
kind: ConfigMap
metadata:
  name: deviceshifu-hikvision-configmap
  namespace: deviceshifu
data:
  driverProperties: |
    driverImage: "defaultImage"
    driverSku: "Hello"
  instructions: |
    instructionSettings:
      defaultTimeoutSeconds: -1
    instructions:
      "capture":
      "info":
      "move/down":
      "move/left":
      "move/right":
      "move/up":
      "stream":
  telemetries: |
    telemetrySettings:
      telemetryUpdateIntervalInMilliseconds: 6000
    telemetries:
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-hikvision-deployment
  name: deviceshifu-hikvision-service
  namespace: deviceshifu
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: deviceshifu-hikvision-deployment
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceshifu-hikvision-deployment
  name: deviceshifu-hikvision-deployment
  namespace: deviceshifu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-hikvision-deployment
  template:
    metadata:
      labels:
       app: deviceshifu-hikvision-deployment
    spec:
      containers:
        - image: edgehub/deviceshifu-http-http:v0.29.0
          name: deviceimg
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: deviceshifu-config
              mountPath: "/etc/edgedevice/config"
              readOnly: true
          env:
            - name: EDGEDEVICE_NAME
              value: edgedevice-hikvision
            - name: EDGEDEVICE_NAMESPACE
              value: devices
        - image: edgenesis/camera-python:v0.0.5
          name: camera-python
          ports: 
          - containerPort: 11112
          env:
          - name: EDGEDEVICE_NAME
            value: "edgedevice-camera"
          - name: EDGEDEVICE_NAMESPACE
            value: "devices"
          - name: IP_CAMERA_ADDRESS
            value: "bj-hikcamera-01.saifai.cn"
          - name: IP_CAMERA_CONTAINER_PORT
            value: "11112"
          - name: IP_CAMERA_HTTP_PORT
            value: "41080"
          - name: IP_CAMERA_PASSWORD
            value: "HelloShifu"
          - name: IP_CAMERA_RTSP_PORT
            value: "41554"
          - name: IP_CAMERA_USERNAME
            value: "guest"
          - name: PYTHONUNBUFFERED
            value: "1"
      volumes:
      - name: deviceshifu-config
        configMap:
          name: deviceshifu-hikvision-configmap
      serviceAccountName: edgedevice-sa
---
apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-hikvision
  namespace: devices
spec:
  sku: "model"
  connection: Ethernet
  address: "localhost:11112"
  protocol: HTTP
